remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: [Kyles Reading Notes]
description: [Documentation of my learnings and observations during the corresponding courses at Code Fellows]
